//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoAventura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Evento_Desportivo = new HashSet<Evento_Desportivo>();
        }
    
        public string Nome { get; set; }
        public decimal NIF { get; set; }
        public Nullable<decimal> CC { get; set; }
        public string Morada { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string existente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento_Desportivo> Evento_Desportivo { get; set; }
    }
}
