//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoAventura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Desportivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento_Desportivo()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int Id_Evento { get; set; }
        public int ano { get; set; }
        public Nullable<System.DateTime> data_da_realização { get; set; }
        public Nullable<System.DateTime> data_limite_pagamento { get; set; }
        public Nullable<System.DateTime> fim_data_subscrição { get; set; }
        public Nullable<System.DateTime> inicio_data_subscrição { get; set; }
        public Nullable<int> idade_min { get; set; }
        public Nullable<int> idade_max { get; set; }
        public string estado { get; set; }
        public Nullable<int> min_participantes { get; set; }
        public Nullable<int> max_participantes { get; set; }
        public string descrição { get; set; }
        public Nullable<decimal> preço_por_participante { get; set; }
        public Nullable<bool> Processed { get; set; }
    
        public virtual canoagem canoagem { get; set; }
        public virtual ciclismo ciclismo { get; set; }
        public virtual escalada escalada { get; set; }
        public virtual trail trail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
