//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoAventura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoAventuraEntities : DbContext
    {
        public SoAventuraEntities()
            : base("name=SoAventuraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<canoagem> canoagem { get; set; }
        public virtual DbSet<ciclismo> ciclismo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<escalada> escalada { get; set; }
        public virtual DbSet<Evento_Desportivo> Evento_Desportivo { get; set; }
        public virtual DbSet<MailsEnviados> MailsEnviados { get; set; }
        public virtual DbSet<trail> trail { get; set; }
    
        [DbFunction("SoAventuraEntities", "EventosCancelados")]
        public virtual IQueryable<EventosCancelados_Result> EventosCancelados(Nullable<System.DateTime> iNICIO, Nullable<System.DateTime> fIM)
        {
            var iNICIOParameter = iNICIO.HasValue ?
                new ObjectParameter("INICIO", iNICIO) :
                new ObjectParameter("INICIO", typeof(System.DateTime));
    
            var fIMParameter = fIM.HasValue ?
                new ObjectParameter("FIM", fIM) :
                new ObjectParameter("FIM", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EventosCancelados_Result>("[SoAventuraEntities].[EventosCancelados](@INICIO, @FIM)", iNICIOParameter, fIMParameter);
        }
    
        [DbFunction("SoAventuraEntities", "EventosDisponiveis")]
        public virtual IQueryable<EventosDisponiveis_Result> EventosDisponiveis(Nullable<System.DateTime> iNICIO, Nullable<System.DateTime> fIM)
        {
            var iNICIOParameter = iNICIO.HasValue ?
                new ObjectParameter("INICIO", iNICIO) :
                new ObjectParameter("INICIO", typeof(System.DateTime));
    
            var fIMParameter = fIM.HasValue ?
                new ObjectParameter("FIM", fIM) :
                new ObjectParameter("FIM", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EventosDisponiveis_Result>("[SoAventuraEntities].[EventosDisponiveis](@INICIO, @FIM)", iNICIOParameter, fIMParameter);
        }
    
        [DbFunction("SoAventuraEntities", "FaturasPorAno")]
        public virtual IQueryable<FaturasPorAno_Result> FaturasPorAno(Nullable<int> aNO, Nullable<decimal> mONTANTEMINIMO, Nullable<decimal> mONTANTEMAXIMO)
        {
            var aNOParameter = aNO.HasValue ?
                new ObjectParameter("ANO", aNO) :
                new ObjectParameter("ANO", typeof(int));
    
            var mONTANTEMINIMOParameter = mONTANTEMINIMO.HasValue ?
                new ObjectParameter("MONTANTEMINIMO", mONTANTEMINIMO) :
                new ObjectParameter("MONTANTEMINIMO", typeof(decimal));
    
            var mONTANTEMAXIMOParameter = mONTANTEMAXIMO.HasValue ?
                new ObjectParameter("MONTANTEMAXIMO", mONTANTEMAXIMO) :
                new ObjectParameter("MONTANTEMAXIMO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FaturasPorAno_Result>("[SoAventuraEntities].[FaturasPorAno](@ANO, @MONTANTEMINIMO, @MONTANTEMAXIMO)", aNOParameter, mONTANTEMINIMOParameter, mONTANTEMAXIMOParameter);
        }
    
        public virtual int DeleteCliente(Nullable<int> nIF)
        {
            var nIFParameter = nIF.HasValue ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCliente", nIFParameter);
        }
    
        public virtual int EnviarMailIntervalo(Nullable<int> dias)
        {
            var diasParameter = dias.HasValue ?
                new ObjectParameter("Dias", dias) :
                new ObjectParameter("Dias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviarMailIntervalo", diasParameter);
        }
    
        public virtual int InsertCliente(string nome, ObjectParameter nIF, Nullable<decimal> cC, string morada, string email, Nullable<System.DateTime> data_nascimento)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var cCParameter = cC.HasValue ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(decimal));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("Morada", morada) :
                new ObjectParameter("Morada", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var data_nascimentoParameter = data_nascimento.HasValue ?
                new ObjectParameter("data_nascimento", data_nascimento) :
                new ObjectParameter("data_nascimento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCliente", nomeParameter, nIF, cCParameter, moradaParameter, emailParameter, data_nascimentoParameter);
        }
    
        public virtual int InsertEvento(ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEvento", ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter);
        }
    
        public virtual int InsertEventoCanoagem(ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> dificuldade)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var dificuldadeParameter = dificuldade.HasValue ?
                new ObjectParameter("dificuldade", dificuldade) :
                new ObjectParameter("dificuldade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEventoCanoagem", ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, dificuldadeParameter);
        }
    
        public virtual int InsertEventoCiclismo(ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> distancia)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("distancia", distancia) :
                new ObjectParameter("distancia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEventoCiclismo", ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, distanciaParameter);
        }
    
        public virtual int InsertEventoEscalada(ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> dificuldade)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var dificuldadeParameter = dificuldade.HasValue ?
                new ObjectParameter("dificuldade", dificuldade) :
                new ObjectParameter("dificuldade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEventoEscalada", ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, dificuldadeParameter);
        }
    
        public virtual int InsertEventoTrail(ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> distancia)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("distancia", distancia) :
                new ObjectParameter("distancia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEventoTrail", ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, distanciaParameter);
        }
    
        public virtual int PagarSubscricao(Nullable<int> id_Evento, Nullable<int> ano, ObjectParameter id_Factura, Nullable<decimal> montante, Nullable<decimal> nIF)
        {
            var id_EventoParameter = id_Evento.HasValue ?
                new ObjectParameter("Id_Evento", id_Evento) :
                new ObjectParameter("Id_Evento", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var montanteParameter = montante.HasValue ?
                new ObjectParameter("montante", montante) :
                new ObjectParameter("montante", typeof(decimal));
    
            var nIFParameter = nIF.HasValue ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PagarSubscricao", id_EventoParameter, anoParameter, id_Factura, montanteParameter, nIFParameter);
        }
    
        public virtual int RemoveEvento(ObjectParameter id_Evento, ObjectParameter ano)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveEvento", id_Evento, ano);
        }
    
        public virtual int SendMail(Nullable<decimal> nIF, string mSG)
        {
            var nIFParameter = nIF.HasValue ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(decimal));
    
            var mSGParameter = mSG != null ?
                new ObjectParameter("MSG", mSG) :
                new ObjectParameter("MSG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SendMail", nIFParameter, mSGParameter);
        }
    
        public virtual int SubscreverClienteEvento(Nullable<int> id_Evento, Nullable<int> ano, Nullable<decimal> nIF)
        {
            var id_EventoParameter = id_Evento.HasValue ?
                new ObjectParameter("Id_Evento", id_Evento) :
                new ObjectParameter("Id_Evento", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var nIFParameter = nIF.HasValue ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubscreverClienteEvento", id_EventoParameter, anoParameter, nIFParameter);
        }
    
        public virtual int UpdateCliente(string nome, ObjectParameter nIF, Nullable<decimal> cC, string morada, string email, Nullable<System.DateTime> data_nascimento)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var cCParameter = cC.HasValue ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(decimal));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("Morada", morada) :
                new ObjectParameter("Morada", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var data_nascimentoParameter = data_nascimento.HasValue ?
                new ObjectParameter("data_nascimento", data_nascimento) :
                new ObjectParameter("data_nascimento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCliente", nomeParameter, nIF, cCParameter, moradaParameter, emailParameter, data_nascimentoParameter);
        }
    
        public virtual int UpdateEvento(ObjectParameter id_Evento, ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEvento", id_Evento, ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter);
        }
    
        public virtual int UpdateEventoCanoagem(ObjectParameter id_Evento, ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> dificuldade)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var dificuldadeParameter = dificuldade.HasValue ?
                new ObjectParameter("dificuldade", dificuldade) :
                new ObjectParameter("dificuldade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEventoCanoagem", id_Evento, ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, dificuldadeParameter);
        }
    
        public virtual int UpdateEventoCiclismo(ObjectParameter id_Evento, ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> distancia)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("distancia", distancia) :
                new ObjectParameter("distancia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEventoCiclismo", id_Evento, ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, distanciaParameter);
        }
    
        public virtual int UpdateEventoEscalada(ObjectParameter id_Evento, ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> dificuldade)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var dificuldadeParameter = dificuldade.HasValue ?
                new ObjectParameter("dificuldade", dificuldade) :
                new ObjectParameter("dificuldade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEventoEscalada", id_Evento, ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, dificuldadeParameter);
        }
    
        public virtual int UpdateEventoTrail(ObjectParameter id_Evento, ObjectParameter ano, Nullable<System.DateTime> data_da_realização, Nullable<System.DateTime> data_limite_pagamento, Nullable<System.DateTime> fim_data_subscrição, Nullable<System.DateTime> inicio_data_subscrição, Nullable<int> idade_min, Nullable<int> idade_max, string estado, Nullable<int> min_participantes, Nullable<int> max_participantes, string descrição, Nullable<decimal> preço_por_participante, Nullable<int> distancia)
        {
            var data_da_realizaçãoParameter = data_da_realização.HasValue ?
                new ObjectParameter("data_da_realização", data_da_realização) :
                new ObjectParameter("data_da_realização", typeof(System.DateTime));
    
            var data_limite_pagamentoParameter = data_limite_pagamento.HasValue ?
                new ObjectParameter("data_limite_pagamento", data_limite_pagamento) :
                new ObjectParameter("data_limite_pagamento", typeof(System.DateTime));
    
            var fim_data_subscriçãoParameter = fim_data_subscrição.HasValue ?
                new ObjectParameter("fim_data_subscrição", fim_data_subscrição) :
                new ObjectParameter("fim_data_subscrição", typeof(System.DateTime));
    
            var inicio_data_subscriçãoParameter = inicio_data_subscrição.HasValue ?
                new ObjectParameter("inicio_data_subscrição", inicio_data_subscrição) :
                new ObjectParameter("inicio_data_subscrição", typeof(System.DateTime));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(int));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var min_participantesParameter = min_participantes.HasValue ?
                new ObjectParameter("min_participantes", min_participantes) :
                new ObjectParameter("min_participantes", typeof(int));
    
            var max_participantesParameter = max_participantes.HasValue ?
                new ObjectParameter("max_participantes", max_participantes) :
                new ObjectParameter("max_participantes", typeof(int));
    
            var descriçãoParameter = descrição != null ?
                new ObjectParameter("descrição", descrição) :
                new ObjectParameter("descrição", typeof(string));
    
            var preço_por_participanteParameter = preço_por_participante.HasValue ?
                new ObjectParameter("preço_por_participante", preço_por_participante) :
                new ObjectParameter("preço_por_participante", typeof(decimal));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("distancia", distancia) :
                new ObjectParameter("distancia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEventoTrail", id_Evento, ano, data_da_realizaçãoParameter, data_limite_pagamentoParameter, fim_data_subscriçãoParameter, inicio_data_subscriçãoParameter, idade_minParameter, idade_maxParameter, estadoParameter, min_participantesParameter, max_participantesParameter, descriçãoParameter, preço_por_participanteParameter, distanciaParameter);
        }
    
        public virtual int VerificarEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarEstados");
        }
    }
}
